swagger: "2.0"
info:
  description: "This is the documentation of the AMT Project 2"
  version: "1.0.0"
  title: "AMT - Project 2"

host: "localhost:8080"
basePath: "/api"
tags:
- name: "user"
  description: "Operations about user"
paths:
  /user/login:
    get:
      tags:
      - "user"
      summary: "Gets the login page"
      description: ""
      operationId: "GetLoginPage"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
    post:
      tags:
      - "user"
      summary: "Connect to the application"
      description: ""
      operationId: "loginUser"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "query"
        description: "The user name for login"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "The password for login in clear text"
        required: true
        type: "string"
      responses:
        default:
          description: "successful operation"
  /user/create:
    get:
      tags:
      - "user"
      summary: "Gets the registration page"
      description: ""
      operationId: "getPageRegistration"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
    post:
      tags:
      - "user"
      summary: "Create a user"
      description: ""
      operationId: "createUser"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "query"
        description: "The user name for login"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "The password for login in clear text"
        required: true
        type: "string"
      - name: "email"
        in: "query"
        description: "The password for login in clear text"
        required: true
        type: "string"
      responses:
        default:
          description: "successful operation"
  /user/password:
    post:
      tags:
      - "user"
      summary: "Create a user"
      description: ""
      operationId: "def"
      produces:
      - "application/json"
      parameters:
      - name: "id_user"
        in: "path"
        description: ""
        required: true
        type: "integer"
        format: "int64"
      responses:
        default:
          description: "successful operation"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      firstname:
        type: "string"
      lastname:
        type: "string"
      username:
        type: "string"
      password:
        type: "string"
      email:
        type: "string"
    xml:
      name: "User"